language: ruby
rvm:
  - 2.1
install:
  - script/cached-bundle install --deployment --without development extra --jobs 3 --retry 3
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - karcher@u.northwestern.edu
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://styles-update.zotero.org:8827/
    on_success: always
    on_failure: never
env:
  global:
    - BUNDLE_ARCHIVE="styles_bundle.cache"
    - AWS_S3_BUCKET="citationstyles-cache"
    - secure: GuOUVKCpBFXnQtR8ZkYehcdkVu79Ay9kbHR9ViQaPqN7H0rLgHb7LB3Is1ati85IigK26YaRX+c55rHErED2d/f6kAMvkYDCP5tCG00hll+ehbZLtxHdl/556i/pHYAmNRcHr1eWHsLSVcXtzAydyPUivhMEVxhwHhu2uyJGzCg=