language: ruby
bundler_args: --without extra
rvm:
  - 1.9.3
env:
  - CONTINUOUS_INTEGRATION=true
notifications:
  email:
    recipients:
      - rintze.zelle@gmail.com
      - sylvester@keil.or.at
      - karcher@u.northwestern.edu
      - charles.parnot@gmail.com
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - http://pinux.info/csls13184719/
    on_success: always
    on_failure: never
